### ISSUE TITLE
Use nouns as class names not verbs

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/LabelsManager#5]
For instance [while the file itself is nicely named as a noun `labels_manipulator`, the class is named `LabelsManipulate`](https://github.com/SebastianoF/nilabel/blob/master/nilabel/agents/labels_manipulator.py). This is applicable to other similar cases within the codebase. The rationale here is that each instance of a class is a "worker" (class) that "does some work" (method).

As a side-note, I'd rather name this class `LabelManipulator` rather than using the plural of the word "label".

**Comment by SebastianoF** [comment]
I kept it plural as the class is dealing with labels rather than label. 

Now the question. Should I call the whole package `nilabels` instead of `nilabel`?
This would prevent from using `nil` or `NiL`. Instead `nis` or `NiS`, after comment in issue #4 .

... I'm afraid I have the answer...

**Comment by dzhoshkun** [comment]
Re: nilabel or nilabels, I think nilabel is nicer. This is your library's name, it should be catchy, and easy to pronouce. nilabel nails it in that regards :) I wouldn't use the plural.
